"""add prompt taxonomy fields for excel import and own-brand exclusion

Revision ID: 7973895f680a
Revises: c3965c6e6fdb
Create Date: 2026-07-28 13:53:47.615417

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7973895f680a"
down_revision: Union[str, Sequence[str], None] = "c3965c6e6fdb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 기존 Target enum(prompt_target)에 새 값 추가 — SQLAlchemy는 Enum 컬럼에 파이썬 멤버의
    # .value가 아니라 .name을 저장하므로(예: Target.C_LEVEL -> 'C_LEVEL') 여기서도 'COMMON'을
    # 추가한다. 이 트랜잭션 안에서 'COMMON' 값을 바로 사용하는 INSERT/UPDATE는 없으므로 PG 12+
    # 에서 트랜잭션 내 ADD VALUE로 안전하다.
    op.execute("ALTER TYPE prompt_target ADD VALUE IF NOT EXISTS 'COMMON'")

    # add_column은 create_table과 달리 새 Enum 타입을 자동으로 만들어주지 않는다 — 먼저
    # CREATE TYPE으로 타입 자체를 만든 뒤 add_column에서 참조해야 한다.
    funnel_intent_enum = sa.Enum(
        "PROBLEM_AWARENESS",
        "SOLUTION_COMPARISON",
        "VENDOR_SELECTION",
        "INFO_SEARCH",
        name="prompt_funnel_intent",
    )
    brand_type_enum = sa.Enum(
        "NON_BRAND_LONGTAIL",
        "CATEGORY_REPRESENTATIVE",
        "COMPETITIVE_COMPARISON",
        "OWN_BRAND",
        name="prompt_brand_type",
    )
    phrasing_enum = sa.Enum("SEARCH_QUERY", "QUESTION", name="prompt_phrasing")
    source_enum = sa.Enum("MANUAL", "EXCEL_IMPORT", name="prompt_source")
    bind = op.get_bind()
    funnel_intent_enum.create(bind, checkfirst=True)
    brand_type_enum.create(bind, checkfirst=True)
    phrasing_enum.create(bind, checkfirst=True)
    source_enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("prompt", sa.Column("industry", sa.String(length=100), nullable=True))
    op.add_column("prompt", sa.Column("service_line", sa.String(length=100), nullable=True))
    op.add_column("prompt", sa.Column("trade_lane", sa.String(length=100), nullable=True))
    op.add_column("prompt", sa.Column("funnel_intent", funnel_intent_enum, nullable=True))
    op.add_column("prompt", sa.Column("brand_type", brand_type_enum, nullable=True))
    op.add_column("prompt", sa.Column("phrasing", phrasing_enum, nullable=True))
    op.add_column("prompt", sa.Column("topic_group", sa.String(length=150), nullable=True))
    # 기존 42개 row가 이미 있으므로 NOT NULL 컬럼은 서버 기본값이 있어야 추가할 수 있다 —
    # 기존 프롬프트는 전부 관리자가 직접 등록한 것이므로 'MANUAL'이 맞는 값이다.
    op.add_column(
        "prompt",
        sa.Column("source", source_enum, nullable=False, server_default="MANUAL"),
    )
    op.add_column("prompt", sa.Column("source_file", sa.String(length=255), nullable=True))
    op.add_column("prompt", sa.Column("imported_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_prompt_brand_type"), "prompt", ["brand_type"], unique=False)
    op.create_index(op.f("ix_prompt_topic_group"), "prompt", ["topic_group"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prompt_topic_group"), table_name="prompt")
    op.drop_index(op.f("ix_prompt_brand_type"), table_name="prompt")
    op.drop_column("prompt", "imported_at")
    op.drop_column("prompt", "source_file")
    op.drop_column("prompt", "source")
    op.drop_column("prompt", "topic_group")
    op.drop_column("prompt", "phrasing")
    op.drop_column("prompt", "brand_type")
    op.drop_column("prompt", "funnel_intent")
    op.drop_column("prompt", "trade_lane")
    op.drop_column("prompt", "service_line")
    op.drop_column("prompt", "industry")
    # ### end Alembic commands ###
