"""initial schema

Revision ID: c3965c6e6fdb
Revises: 
Create Date: 2026-07-15 19:26:54.953836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3965c6e6fdb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repeat_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_own', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('llm_provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('model_string', sa.String(length=100), nullable=False),
    sa.Column('supports_web_search', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('prompt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=100), nullable=False),
    sa.Column('target', sa.Enum('C_LEVEL', 'MANAGER', 'PRACTITIONER', 'JUNIOR', 'SELLER', name='prompt_target'), nullable=False),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='prompt_priority'), nullable=False),
    sa.Column('language', sa.Enum('KO', 'EN', name='prompt_language'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supersedes_id'], ['prompt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_supersedes_id'), 'prompt', ['supersedes_id'], unique=False)
    op.create_table('brand_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('alias_text', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'alias_text', name='uq_brand_alias_brand_id_alias_text')
    )
    op.create_index(op.f('ix_brand_alias_brand_id'), 'brand_alias', ['brand_id'], unique=False)
    op.create_table('brand_domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_index(op.f('ix_brand_domain_brand_id'), 'brand_domain', ['brand_id'], unique=False)
    op.create_table('execution_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('llm_provider_id', sa.Integer(), nullable=False),
    sa.Column('repeat_index', sa.Integer(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='execution_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.CheckConstraint('repeat_index >= 0', name='ck_execution_run_repeat_index_non_negative'),
    sa.ForeignKeyConstraint(['llm_provider_id'], ['llm_provider.id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'prompt_id', 'llm_provider_id', 'repeat_index', name='uq_execution_run_batch_prompt_provider_repeat')
    )
    op.create_index(op.f('ix_execution_run_batch_id'), 'execution_run', ['batch_id'], unique=False)
    op.create_index(op.f('ix_execution_run_llm_provider_id'), 'execution_run', ['llm_provider_id'], unique=False)
    op.create_index('ix_execution_run_prompt_batch', 'execution_run', ['prompt_id', 'batch_id'], unique=False)
    op.create_index(op.f('ix_execution_run_prompt_id'), 'execution_run', ['prompt_id'], unique=False)
    op.create_table('weekly_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_label', sa.String(length=20), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('llm_provider_id', sa.Integer(), nullable=True),
    sa.Column('sov', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('avg_rank', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('sentiment_positive_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('sentiment_neutral_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('sentiment_negative_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('citation_share_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('total_runs', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['llm_provider_id'], ['llm_provider.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_label', 'brand_id', 'llm_provider_id', name='uq_weekly_snapshot_week_brand_provider')
    )
    op.create_index(op.f('ix_weekly_snapshot_brand_id'), 'weekly_snapshot', ['brand_id'], unique=False)
    op.create_index('ix_weekly_snapshot_brand_provider_week', 'weekly_snapshot', ['brand_id', 'llm_provider_id', 'week_label'], unique=False)
    op.create_index(op.f('ix_weekly_snapshot_llm_provider_id'), 'weekly_snapshot', ['llm_provider_id'], unique=False)
    op.create_index(op.f('ix_weekly_snapshot_week_label'), 'weekly_snapshot', ['week_label'], unique=False)
    op.create_index('uq_weekly_snapshot_week_brand_all_providers', 'weekly_snapshot', ['week_label', 'brand_id'], unique=True, postgresql_where=sa.text('llm_provider_id IS NULL'))
    op.create_table('citation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_run_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('matched_brand_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['execution_run_id'], ['execution_run.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_brand_id'], ['brand.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citation_domain'), 'citation', ['domain'], unique=False)
    op.create_index(op.f('ix_citation_execution_run_id'), 'citation', ['execution_run_id'], unique=False)
    op.create_index(op.f('ix_citation_matched_brand_id'), 'citation', ['matched_brand_id'], unique=False)
    op.create_table('mention',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_run_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('mention_order', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', name='mention_sentiment'), nullable=False),
    sa.Column('sentiment_evidence', sa.Text(), nullable=True),
    sa.CheckConstraint('mention_order >= 1', name='ck_mention_mention_order_positive'),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['execution_run_id'], ['execution_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_run_id', 'brand_id', name='uq_mention_execution_run_brand')
    )
    op.create_index(op.f('ix_mention_brand_id'), 'mention', ['brand_id'], unique=False)
    op.create_index(op.f('ix_mention_execution_run_id'), 'mention', ['execution_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mention_execution_run_id'), table_name='mention')
    op.drop_index(op.f('ix_mention_brand_id'), table_name='mention')
    op.drop_table('mention')
    op.drop_index(op.f('ix_citation_matched_brand_id'), table_name='citation')
    op.drop_index(op.f('ix_citation_execution_run_id'), table_name='citation')
    op.drop_index(op.f('ix_citation_domain'), table_name='citation')
    op.drop_table('citation')
    op.drop_index('uq_weekly_snapshot_week_brand_all_providers', table_name='weekly_snapshot', postgresql_where=sa.text('llm_provider_id IS NULL'))
    op.drop_index(op.f('ix_weekly_snapshot_week_label'), table_name='weekly_snapshot')
    op.drop_index(op.f('ix_weekly_snapshot_llm_provider_id'), table_name='weekly_snapshot')
    op.drop_index('ix_weekly_snapshot_brand_provider_week', table_name='weekly_snapshot')
    op.drop_index(op.f('ix_weekly_snapshot_brand_id'), table_name='weekly_snapshot')
    op.drop_table('weekly_snapshot')
    op.drop_index(op.f('ix_execution_run_prompt_id'), table_name='execution_run')
    op.drop_index('ix_execution_run_prompt_batch', table_name='execution_run')
    op.drop_index(op.f('ix_execution_run_llm_provider_id'), table_name='execution_run')
    op.drop_index(op.f('ix_execution_run_batch_id'), table_name='execution_run')
    op.drop_table('execution_run')
    op.drop_index(op.f('ix_brand_domain_brand_id'), table_name='brand_domain')
    op.drop_table('brand_domain')
    op.drop_index(op.f('ix_brand_alias_brand_id'), table_name='brand_alias')
    op.drop_table('brand_alias')
    op.drop_index(op.f('ix_prompt_supersedes_id'), table_name='prompt')
    op.drop_table('prompt')
    op.drop_table('llm_provider')
    op.drop_table('brand')
    op.drop_table('batch_config')
    # ### end Alembic commands ###
